# mocha settings
require:
  - ts-node/register
  - source-map-support/register
recursive: true
color: true
exit: true
extension:
  - ts
  - test.ts
ignore:
  # this is so that mocha doesn'T auto execute app.ts before the tests does load it.
  - "**/src/app.ts"
