extends: "@istanbuljs/nyc-config-typescript" # this is to fix broken covered lines
extension:
- ".ts"
- ".tsx"
exclude:
- "**/*.d.ts"
- "**/app.ts"
reporter:
- html
- lcovonly
- clover
# those 2 are for commandline outputs
- text
- text-summary
report-dir: coverage

# Coverage gates
check-coverage: true
functions: 90
lines: 80
statements: 80
branches: 70
